In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://fbref.com/en/comps/12/2021-2022/2021-2022-La-Liga-Stats"
    
# Add headers to mimic a browser request
headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
    }

response = requests.get(url, headers=headers)
response.raise_for_status()
print(response)

<Response [200]>

In [4]:
soup = BeautifulSoup(response.content, "html.parser")

results_table = soup.find('table', {'id': 'results2021-2022121_overall'})
df = pd.read_html(str(results_table))[0]


columns_to_drop = ['Attendance', 'Notes', 'Top Team Scorer', 'Attendance', 'Goalkeeper', 'W', 'L', 'D', 'GF', 'GA', 'GD', 'MP']
df.drop(columns=columns_to_drop, inplace=True)

df

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_19428\618139937.py:4: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(results_table))[0]

    Rk            Squad  Pts  Pts/MP    xG   xGA   xGD  xGD/90
0    1      Real Madrid   86    2.26  71.7  43.9  27.8    0.73
1    2        Barcelona   73    1.92  63.4  34.4  29.0    0.76
2    3  Atlético Madrid   71    1.87  54.4  33.4  21.1    0.56
3    4          Sevilla   70    1.84  42.4  36.9   5.4    0.14
4    5            Betis   65    1.71  53.5  43.4  10.1    0.27
5    6    Real Sociedad   62    1.63  51.5  38.7  12.8    0.34
6    7       Villarreal   59    1.55  64.2  44.8  19.4    0.51
7    8    Athletic Club   55    1.45  49.6  38.4  11.3    0.30
8    9         Valencia   48    1.26  39.0  47.7  -8.7   -0.23
9   10          Osasuna   47    1.24  36.7  46.3  -9.6   -0.25
10  11       Celta Vigo   46    1.21  43.1  45.7  -2.6   -0.07
11  12   Rayo Vallecano   42    1.11  42.8  48.4  -5.6   -0.15
12  13            Elche   42    1.11  33.7  59.1 -25.4   -0.67
13  14         Espanyol   42    1.11  36.7  51.2 -14.5   -0.38
14  15           Getafe   39    1.03  29.3  38.6  -9.3   -0.25
15  16         Mallorca   39    1.03  38.8  49.3 -10.5   -0.28
16  17            Cádiz   39    1.03  39.5  48.3  -8.7   -0.23
17  18          Granada   38    1.00  39.0  61.2 -22.2   -0.59
18  19          Levante   35    0.92  55.1  55.0   0.1    0.00
19  20           Alavés   31    0.82  37.3  57.0 -19.7   -0.52

In [ ]:
df.to_csv('laliga22-table.csv', index=False)