In [2]:
import pandas as pd
import json

In [7]:
# Open the file and load its contents
with open("data/standings.json", "r", encoding="utf-8") as file:
    data = json.load(file)

In [8]:
standings = list()

for i in range(len(data["standings"][0]["rows"])):
    team = data["standings"][0]["rows"][i]["team"]["name"]
    position = data["standings"][0]["rows"][i]["position"]
    points = data["standings"][0]["rows"][i]["points"]
    wins = data["standings"][0]["rows"][i]["wins"]
    draws = data["standings"][0]["rows"][i]["draws"]
    losses = data["standings"][0]["rows"][i]["losses"]
    goals_for = data["standings"][0]["rows"][i]["scoresFor"]
    goals_against = data["standings"][0]["rows"][i]["scoresAgainst"]

    standings.append({
        "Team": team,
        "GoalsFor": goals_for,
        "GoalsAgainst": goals_against,
        "GoalsDifference": goals_for - goals_against,
        "Wins": wins,
        "Draws": draws,
        "Losses": losses,
        "Pts": points,
        "Rank": position
    })

In [9]:
data = pd.DataFrame(standings)
data

,Team,GoalsFor,GoalsAgainst,GoalsDifference,Wins,Draws,Losses,Pts,Rank
0,Man City,4,0,4,1,0,0,3,1
1,Sunderland,3,0,3,1,0,0,3,2
2,Tottenham,3,0,3,1,0,0,3,3
3,Liverpool,4,2,2,1,0,0,3,4
4,Nott'm Forest,3,1,2,1,0,0,3,5
5,Arsenal,1,0,1,1,0,0,3,6
6,Leeds,1,0,1,1,0,0,3,7
7,Brighton,1,1,0,0,1,0,1,8
8,Fulham,1,1,0,0,1,0,1,9
9,Aston Villa,0,0,0,0,1,0,1,10
10,Chelsea,0,0,0,0,1,0,1,11
11,Crystal Palace,0,0,0,0,1,0,1,12
12,Newcastle,0,0,0,0,1,0,1,13
13,Everton,0,1,-1,0,0,1,0,14
14,Man United,0,1,-1,0,0,1,0,15
15,Bournemouth,2,4,-2,0,0,1,0,16
16,Brentford,1,3,-2,0,0,1,0,17
17,Burnley,0,3,-3,0,0,1,0,18
18,West Ham,0,3,-3,0,0,1,0,19
19,Wolves,0,4,-4,0,0,1,0,20

In [10]:
data.to_csv("data/pl25-26.csv", index=False, encoding="utf-8")

In [129]:
# Open the file and load its contents
with open("data/home_standings.json", "r", encoding="utf-8") as file:
    data = json.load(file)

In [ ]:
standings = list()

for i in range(len(data["standings"][0]["rows"])):
    team = data["standings"][0]["rows"][i]["team"]["name"]
    position = data["standings"][0]["rows"][i]["position"]
    points = data["standings"][0]["rows"][i]["points"]
    wins = data["standings"][0]["rows"][i]["wins"]
    draws = data["standings"][0]["rows"][i]["draws"]
    losses = data["standings"][0]["rows"][i]["losses"]
    goals_for = data["standings"][0]["rows"][i]["scoresFor"]
    goals_against = data["standings"][0]["rows"][i]["scoresAgainst"]

    standings.append({
        "Team": team,
        "GoalsFor": goals_for,
        "GoalsAgainst": goals_against,
        "GoalsDifference": goals_for - goals_against,
        "Wins": wins,
        "Draws": draws,
        "Losses": losses,
        "Pts": points,
        "Rank": position
    })

In [131]:
data = pd.DataFrame(standings)
data

,Team,Position,Pts,Wins,Draws,Losses,GoalsFor,GoalsAgainst,GoalsDifference
0,ES Zarzis,1,3,1,0,0,1,0,1
1,Club Africain,2,3,1,0,0,1,0,1
2,Stade Tunisien,3,3,1,0,0,1,0,1
3,Avenir Sportif De La Marsa,4,3,1,0,0,1,0,1
4,JS Omrane,5,3,1,0,0,3,1,2
5,US Ben Guerdane,6,3,1,0,0,2,0,2
6,JS Kairouanaise,7,3,1,0,0,1,0,1
7,Espérance Tunis,8,1,0,1,0,1,1,0
8,ES Métlaoui,9,1,0,1,0,0,0,0
9,Avenir Sportif De Gabes,10,1,0,1,0,0,0,0
10,CA Bizertin,10,1,0,1,0,1,1,0
11,Olympique Béja,11,1,0,1,0,0,0,0
12,US Monastir,12,1,0,1,0,1,1,0
13,CS Sfaxien,14,0,0,0,1,1,2,-1
14,AS Soliman,16,0,0,0,1,0,1,-1
15,Etoile Sportive Du Sahel,16,0,0,0,1,0,1,-1

In [132]:
data.to_csv("data/home_standings2026.csv", index=False, encoding="utf-8")

In [134]:
# Open the file and load its contents
with open("data/away_standings.json", "r", encoding="utf-8") as file:
    data = json.load(file)

In [135]:
standings = list()

for i in range(len(data["standings"][0]["rows"])):
    team = data["standings"][0]["rows"][i]["team"]["name"]
    position = data["standings"][0]["rows"][i]["position"]
    points = data["standings"][0]["rows"][i]["points"]
    wins = data["standings"][0]["rows"][i]["wins"]
    draws = data["standings"][0]["rows"][i]["draws"]
    losses = data["standings"][0]["rows"][i]["losses"]
    goals_for = data["standings"][0]["rows"][i]["scoresFor"]
    goals_against = data["standings"][0]["rows"][i]["scoresAgainst"]

    standings.append({
        "Team": team,
        "Position": position,
        "Pts": points,
        "Wins": wins,
        "Draws": draws,
        "Losses": losses,
        "GoalsFor": goals_for,
        "GoalsAgainst": goals_against,
        "GoalsDifference": goals_for - goals_against,
    })

In [136]:
data = pd.DataFrame(standings)
data

,Team,Position,Pts,Wins,Draws,Losses,GoalsFor,GoalsAgainst,GoalsDifference
0,ES Zarzis,1,3,1,0,0,2,1,1
1,Club Africain,2,3,1,0,0,1,0,1
2,ES Métlaoui,3,3,1,0,0,1,0,1
3,Stade Tunisien,5,1,0,1,0,1,1,0
4,US Monastir,5,1,0,1,0,1,1,0
5,CS Sfaxien,6,1,0,1,0,1,1,0
6,Espérance Tunis,7,1,0,1,0,0,0,0
7,Avenir Sportif De Gabes,8,1,0,1,0,0,0,0
8,CA Bizertin,9,1,0,1,0,0,0,0
9,Avenir Sportif De La Marsa,10,0,0,0,1,0,1,-1
10,JS Omrane,11,0,0,0,1,0,1,-1
11,JS Kairouanaise,12,0,0,0,1,0,1,-1
12,US Ben Guerdane,13,0,0,0,1,0,1,-1
13,AS Soliman,14,0,0,0,1,0,1,-1
14,Etoile Sportive Du Sahel,15,0,0,0,1,1,3,-2
15,Olympique Béja,16,0,0,0,1,0,2,-2

In [137]:
data.to_csv("data/away_standings20260.csv", index=False, encoding="utf-8")